insert into CC (City, Country) values ('New York', 'United States');
insert into CC (City, Country) values ('Cancum', 'Mexico');
insert into CC (City, Country) values ('São Paulo', 'Brazil');
insert into CC (City, Country) values ('Buenos Aires', 'Argentina');
insert into CC (City, Country) values ('Bogotá', 'Colombia');
insert into CC (City, Country) values ('Marrakesh', 'Morocco');
insert into CC (City, Country) values ('Cairo', 'Egypt');
insert into CC (City, Country) values ('Johannesburg', 'South Africa');
insert into CC (City, Country) values ('Madrid', 'Spain');
insert into CC (City, Country) values ('Barcelona', 'Spain');
insert into CC (City, Country) values ('Paris', 'France');
insert into CC (City, Country) values ('Rome', 'Italy');
insert into CC (City, Country) values ('London', 'United Kingdom');
insert into CC (City, Country) values ('Berlin', 'Germany');
insert into CC (City, Country) values ('Amsterdam', 'Netherlands');
insert into CC (City, Country) values ('Vienna', 'Austria');
insert into CC (City, Country) values ('Budapest', 'Hungary');
insert into CC (City, Country) values ('Prague', 'Czech Republic');
insert into CC (City, Country) values ('Warsaw', 'Poland');
insert into CC (City, Country) values ('Moscow', 'Russia');
