insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (1, 'Nondisplaced fracture of right tibial tuberosity, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 3, 3, 66);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (2, 'Congenital kyphosis, thoracolumbar region', 10, 7, 75);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (3, 'Strain of other flexor muscle, fascia and tendon at forearm level, right arm, subsequent encounter', 9, 2, 2);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (4, 'War operations involving explosion of sea-based artillery shell, civilian, sequela', 5, 8, 28);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (5, 'Displaced fracture of body of left talus, subsequent encounter for fracture with delayed healing', 1, 1, 15);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (6, 'Contusion of right great toe with damage to nail, sequela', 9, 6, 95);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (7, 'Toxic effect of hydrogen cyanide', 3, 4, 45);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (8, 'Occupant of streetcar injured in collision with motor vehicle in traffic accident, sequela', 10, 8, 64);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (9, 'Pneumococcal arthritis, hand', 3, 7, 41);
insert into Review (ID, Description, Score, Pack_ID, Cust_ID) values (10, 'Unspecified injury of unspecified muscle(s) and tendon(s) at lower leg level, left leg, subsequent encounter', 10, 3, 17);
