insert into TravelAgency.Airline (ICAO, Name) values ('TAP', 'TAP Air Portugal');
insert into TravelAgency.Airline (ICAO, Name) values ('QTR', 'Qatar Airways');
insert into TravelAgency.Airline (ICAO, Name) values ('UAE', 'Emirates');
insert into TravelAgency.Airline (ICAO, Name) values ('DLH', 'Deutsche Lufthansa AG');
insert into TravelAgency.Airline (ICAO, Name) values ('AFR', 'Air France');
insert into TravelAgency.Airline (ICAO, Name) values ('KLM', 'KLM');
insert into TravelAgency.Airline (ICAO, Name) values ('BAW', 'British Airways');
insert into TravelAgency.Airline (ICAO, Name) values ('IBE', 'Iberia');
insert into TravelAgency.Airline (ICAO, Name) values ('TAM', 'LATAM Airlines Brasil');
insert into TravelAgency.Airline (ICAO, Name) values ('DSM', 'LATAM Airlines Argentina');
insert into TravelAgency.Airline (ICAO, Name) values ('ARE', 'LATAM Airlines Colômbia');
insert into TravelAgency.Airline (ICAO, Name) values ('BEL', 'Brussels Airlines');
insert into TravelAgency.Airline (ICAO, Name) values ('VLG', 'Vueling Airlines');
insert into TravelAgency.Airline (ICAO, Name) values ('RAM', 'Royal Air Maroc');
insert into TravelAgency.Airline (ICAO, Name) values ('SAT', 'SATA Air Açores');
insert into TravelAgency.Airline (ICAO, Name) values ('LGL', 'Luxair');
insert into TravelAgency.Airline (ICAO, Name) values ('AEA', 'Air Europa');
insert into TravelAgency.Airline (ICAO, Name) values ('ACA', 'Air Canada');
insert into TravelAgency.Airline (ICAO, Name) values ('RZO', 'Azores Airlines');