insert into Accommodation (ID, Name, Description, Price, CC_Location) values (1, 'Bode LLC', null, '€120,52', 'London');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (2, 'Ratke, Weissnat and Mraz', 'Nondisplaced fracture of neck of left talus', '€201,00', 'Vienna');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (3, 'Kunde-VonRueden', null, '€102,48', 'Prague');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (4, 'Hahn-Reinger', null, '€219,75', 'Madrid');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (5, 'Kling Group', null, '€176,99', 'New York');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (6, 'Purdy, Mohr and Bahringer', null, '€64,04', 'Marrakesh');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (7, 'Volkman-Murray', 'Contusion and laceration of right cerebrum with loss of consciousness of any duration with death due to other cause prior to regaining consciousness', '€227,89', 'Cairo');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (8, 'Kilback-Waters', null, '€190,28', 'Johannesburg');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (9, 'Satterfield Inc', 'Cerebral infarction due to thrombosis of middle cerebral artery', '€286,17', 'Johannesburg');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (10, 'Cassin-Stokes', null, '€63,49', 'Prague');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (11, 'Zieme, Schoen and Wintheiser', null, '€238,53', 'New York');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (12, 'Pagac-Purdy', null, '€245,93', 'Paris');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (13, 'McKenzie-O''Hara', null, '€215,46', 'London');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (14, 'Johnson and Sons', 'Crushing injury of neck, part unspecified, sequela', '€116,33', 'Bogotá');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (15, 'Durgan Group', null, '€192,55', 'London');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (16, 'Kohler-Zboncak', null, '€89,37', 'Paris');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (17, 'Treutel-O''Conner', null, '€101,70', 'Rome');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (18, 'Kertzmann-O''Keefe', null, '€166,09', 'Cancum');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (19, 'Batz Inc', null, '€277,85', 'Barcelona');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (20, 'Cremin-Douglas', null, '€282,74', 'Cairo');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (21, 'Jacobson Group', null, '€181,84', 'Amsterdam');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (22, 'Senger-Braun', null, '€142,25', 'São Paulo');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (23, 'Hyatt, D''Amore and Price', null, '€106,46', 'Prague');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (24, 'Brown LLC', null, '€236,17', 'Paris');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (25, 'Mills, Balistreri and Koelpin', null, '€290,50', 'Paris');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (26, 'Kerluke-Pagac', null, '€70,54', 'Marrakesh');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (27, 'Berge LLC', null, '€105,75', 'Moscow');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (28, 'Shields Group', null, '€189,67', 'Warsaw');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (29, 'Armstrong, Prosacco and Braun', null, '€286,36', 'Amsterdam');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (30, 'Corwin Inc', 'Malignant pleural effusion', '€164,18', 'Prague');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (31, 'Pouros LLC', null, '€115,90', 'New York');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (32, 'Gislason, Turcotte and Raynor', null, '€151,54', 'Madrid');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (33, 'Lowe Inc', null, '€267,44', 'Madrid');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (34, 'Hammes Inc', null, '€83,41', 'Cairo');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (35, 'Halvorson, Bayer and Daniel', 'Other paralytic syndrome following other cerebrovascular disease, bilateral', '€221,96', 'Rome');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (36, 'Denesik Inc', null, '€299,32', 'Berlin');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (37, 'Stoltenberg, Feil and Turner', null, '€131,75', 'Johannesburg');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (38, 'Ankunding Group', null, '€173,73', 'Berlin');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (39, 'Witting, Labadie and McLaughlin', null, '€184,36', 'Berlin');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (40, 'Gottlieb, Waters and Flatley', 'Other injury due to other accident on board merchant ship, sequela', '€218,82', 'London');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (41, 'Bahringer-Leffler', 'Displaced fracture of middle third of navicular [scaphoid] bone of left wrist, subsequent encounter for fracture with malunion', '€197,92', 'São Paulo');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (42, 'Lowe-Grimes', 'Laceration without foreign body, right hip', '€69,30', 'Rome');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (43, 'Nikolaus-Collins', null, '€261,16', 'Cancum');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (44, 'Upton Group', null, '€81,70', 'Madrid');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (45, 'Beier LLC', null, '€107,02', 'Paris');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (46, 'Smith LLC', null, '€195,64', 'Budapest');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (47, 'Medhurst-Breitenberg', null, '€254,70', 'Budapest');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (48, 'Schinner and Sons', null, '€237,24', 'Rome');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (49, 'Kautzer and Sons', null, '€74,84', 'Berlin');
insert into Accommodation (ID, Name, Description, Price, CC_Location) values (50, 'Wiza Group', null, '€83,14', 'São Paulo');

insert into Accommodation (ID, Name, Image, Description, Price, CC_Location)
SELECT 1, 'Bode LLC', BulkColumn, '€120,52', 'London'
FROM Openrowset(Bulk 'C:\Users\marci\Desktop\BD_Projeto\BD_travel_agency\Images\hotel1.jpg', Single_Blob) as image